var cnames=["AFGHANISTAN","ALGERIA","ANDORRA","ANGOLA","ALBANIA",
"ANTIGUA & BARBUDA","ARGENTINA","ARMENIA","AUSTRALIA","AUSTRIA",
"AZERBAIJAN",
"BAHAMAS","BAHRAIN","BANGLADESH","BARBADOS","BELARUS","BELGIUM","BELIZE","BENIN","BHUTAN","BOLIVIA","BOSNIA & HERZEGOVINA","BOTSWANA",
"BRAZIL","BRUNEI DARUSSALAM","BULGARIA","BURKINA FASO","BURUNDI",
"CAMBODIA","CAMEROON","CANADA","CAPE VERDE","CENTRAL AFRICAN REPUBLIC","CHAD","CHILE","CHINA","COLOMBIA","COMOROS","CONGO","COSTA RICA","CROATIA",
"CUBA","CYPRUS","CZECH REPUBLIC",
"DENMARK","DJIBOUTI","DOMINICAN REPUBLIC","DOMINICA",
"ECUADOR","EGYPT","EL SALVADOR","EQUATORIAL GUINEA","ERITREA","ESTONIA","ETHIOPIA",
"FIJI","FINLAND","FRANCE",
"GABON","GAMBIA","GEORGIA","GERMANY","GHANA","GREAT BRITAIN","GREECE","GRENADA","GUATEMALA","GUINEA","GUINEA-BISSAU","GUYANA",
"HAITI","HONDURAS","HUNGARY",
"ICELAND","INDIA","INDONESIA","IRAN","IRAQ","IRELAND","ISRAEL AND THE OCCUPIED TERRITORIES","ITALY",
"JAMAICA","JAPAN","JORDAN",
"KAZAKHSTAN","KENYA","KUWAIT","KYRGYZ REPUBLIC",
"LAOS","LATVIA","LEBANON","LESOTHO","LIBERIA","LIBYA","LIECHTENSTEIN","LITHUANIA","LUXEMBOURG",

"REPUBLIC OF MACEDONIA","MADAGASCAR","MALAWI","MALAYSIA","MALDIVES","MALI","MALTA","MAURITANIA","MAURITIUS","MEXICO","MOLDOVA","MONACO","MONGOLIA","MONTENEGRO",
"MOROCCO","MOZAMBIQUE","MYANMAR",

"NAMIBIA","NAURU","NEPAL","NETHERLANDS","NEW ZEALAND","NICARAGUA","NIGER","NIGERIA","NORTH KOREA",
"NORWAY","OMAN","PAKISTAN","PALAU","PANAMA",
"PAPUA NEW GUINEA","PARAGUAY","PERU","PHILIPPINES","POLAND","PORTUGAL","QATAR","ROMANIA",
"RUSSIAN FEDERATION","RWANDA","SAINT KITTS AND NEVIS","SAINT LUCIA","SAINT VINCENT'S & GRENADINES",
"SAMOA","SAN MARINO","SAO TOME AND PRINCIPE","SAUDI ARABIA","SENEGAL","SERBIA","SEYCHELLES","SIERRA LEONE","SINGAPORE","SLOVAK REPUBLIC",
"SLOVENIA","SOLOMON ISLANDS","SOMALIA","SOUTH AFRICA","SOUTH KOREA","SPAIN","SRI LANKA","SUDAN","SURINAME",
"SWAZILAND","SWEDEN","SWITZERLAND","SYRIA","TAJIKISTAN","TAIWAN","TANZANIA","THAILAND","TIMOR LESTE","TOGO","TONGA",
"TRINIDAD & TOBAGO","TUNISIA",
"TURKEY","TURKMENISTAN","TUVALU","UGANDA","UKRAINE","UNITED ARAB EMIRATES","UNITED STATES OF AMERICA ","URUGUAY"
,"UZBEKISTAN","VANUATU","VENEZUELA","VIETNAM","WESTERN SAHARA","YEMEN","ZAMBIA","ZIMBABWE"]

var fnames=["af.png","dz.png","ad.png","ao.png","al.png",
"ag.png","ar.png","am.png","au.png","at.png","az.png",
"bs.png","bh.png","bd.png","bb.png","by.png","be.png","bz.png","bj.png","bt.png","bo.png","ba.png","bw.png","br.png",
"bn.png","bg.png" ,"bf.png","bi.png",
"kh.png" ,"cm.png" ,"ca.png" ,"cv.png","cf.png","td.png","cl.png" ,"cn.png" ,"co.png","km.png" ,"cg.png","cr.png","hr.png","cu.png","cy.png","cz.png",
"dk.png","dj.png","do.png","dm.png",
"ec.png","eg.png","sv.png","gq.png","er.png","ee.png","et.png",
"fj.png","fi.png","fr.png",
"ga.png","gm.png","ge.png","de.png","gh.png","gb.png","gr.png","gd.png","gt.png","gn.png","gw.png","gy.png",
"ht.png","hn.png","hu.png",
"is.png","in.png","id.png","ir.png","iq.png","ie.png","il.png","it.png",
"jm.png","jp.png","jo.png",
"kz.png","ke.png","kw.png","kg.png",
"la.png","lv.png","lb.png","ls.png","lr.png","ly.png","li.png","lt.png","lu.png",
"mk.png","mg.png","mw.png","my.png","mv.png","ml.png",
 "mt.png","mr.png","mu.png","mx.png","md.png","mc.png","mn.png","me.png","ma.png","mz.png","mm.png" ,
 "na.png","nr.png","np.png","nl.png","nz.png","ni.png","ne.png","ng.png","kp.png","no.png",
 "om.png","pk.png","pw.png","pa.png","pg.png","py.png","pe.png","ph.png","pl.png","pt.png","qa.png",
"ro.png","ru.png","rw.png","kn.png","lc.png","vc.png","ws.png","sm.png","st.png","sa.png","sn.png","rs.png","sc.png",
"sl.png","sg.png","sk.png","si.png","sb.png","so.png","za.png","kr.png","es.png","lk.png","sd.png",
"sr.png", "sz.png","se.png","ch.png","sy.png","tj.png","tw.png",
"tz.png","th.png","tl.png","tg.png","to.png","tt.png","tn.png","tr.png","tm.png","tv.png","ug.png","ua.png","ae.png",
"us.png","uy.png","uz.png","vu.png","ve.png","vn.png","eh.png","ye.png","zm.png","zw.png"]